# Pandas for Data Analysis (B1 Level Notes)

In [2]:
import pandas as pd

# Create a DataFrame (like a table)
# Keys are column names, values are data
df = pd.DataFrame({
    "name": ["Ali", "Zara", "Jasur"],     # names
    "age":  [22, 28, 31],                 # ages
    "city": ["Tashkent", "Samarkand", "Bukhara"]  # cities
})

df  # show the table

    name  age       city
0    Ali   22   Tashkent
1   Zara   28  Samarkand
2  Jasur   31    Bukhara

In [3]:
# Select one column → returns Series (1D)
print(type(df['age']))

# Select multiple columns → returns DataFrame (2D)
print(type(df[['name', 'age']]))

# Index = row labels (default: 0,1,2,...)
print(df.index)

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)

In [4]:
# Create your own DataFrame
df2 = pd.DataFrame({
    "student": ["Ali", "Zara", "Jasur", "Madina", "Otabek"],
    "subject": ["Math", "Physics", "Biology", "Math", "Chemistry"],
    "score": [90, 85, 88, 92, 75],
    "city": ["Tashkent", "Samarkand", "Bukhara", "Tashkent", "Samarkand"]
})

# Set 'student' as index (row label)
df2 = df2.set_index('student')

df2

           subject  score       city
student
Ali           Math     90   Tashkent
Zara       Physics     85  Samarkand
Jasur      Biology     88    Bukhara
Madina        Math     92   Tashkent
Otabek   Chemistry     75  Samarkand

In [5]:
# Get one row by index label
print(df2.loc['Ali'])

subject        Math
score            90
city       Tashkent
Name: Ali, dtype: object

In [6]:
# Load example dataset
from sklearn.datasets import load_iris

iris = load_iris(as_frame=True)
df = iris.frame

In [7]:
# Show first 5 rows
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [9]:
# Show number of rows and columns
df.shape
# Show column info (type, null values)
df.info()
# Show statistics (mean, min, max)
df.describe()
# Count missing (null) values
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [10]:
df = pd.DataFrame({
    "name": ["Ali", "Zara", "Jasur"],
    "age":  [22, 28, 31],
    "city": ["Tashkent", "Samarkand", "Bukhara"]
})

print('--- before set_index ---')

# loc → select by label (here index is 0,1,2)
print(df.loc[0])

# iloc → select by position (0 = first row)
print(df.iloc[0])

--- before set_index ---
name         Ali
age           22
city    Tashkent
Name: 0, dtype: object
name         Ali
age           22
city    Tashkent
Name: 0, dtype: object

In [11]:
# Set 'name' as index
df = df.set_index('name')

print('--- after set_index ---')

# loc uses label (name)
print(df.loc['Ali'])

# iloc still uses position
print(df.iloc[0])

# This will give error because 0 is not index anymore
# print(df.loc[0])

--- after set_index ---
age           22
city    Tashkent
Name: Ali, dtype: object
age           22
city    Tashkent
Name: Ali, dtype: object

In [12]:
df = pd.DataFrame({
    "name": ["Ali", "Zara", "Jasur", "Madina", "Otabek"],
    "age":  [22, 28, 31, 17, 45],
    "city": ["Tashkent", "Samarkand", "Bukhara", "Tashkent", "Samarkand"]
})

# Correct filtering:
# & = AND, | = OR
# Use () for each condition
df[(df.age >= 18) & (df.city == 'Tashkent')]

  name  age      city
0  Ali   22  Tashkent

In [13]:
# People older than 25 and not in Tashkent
df[(df.age > 25) & (df.city != 'Tashkent')]
# People in Tashkent OR Bukhara
df[(df.city == 'Tashkent') | (df.city == 'Bukhara')]
# Youngest person
df[df.age == df.age.min()]

     name  age      city
3  Madina   17  Tashkent

In [14]:
# Group by city and calculate average age
df.groupby('city')['age'].mean()

city
Bukhara      31.0
Samarkand    36.5
Tashkent     19.5
Name: age, dtype: float64

In [15]:
# Check result type
result = df.groupby('city')['age'].mean()

print(type(result))  # it is a Series
print(result)

<class 'pandas.core.series.Series'>
city
Bukhara      31.0
Samarkand    36.5
Tashkent     19.5
Name: age, dtype: float64

In [16]:
# Do multiple calculations at once
df.groupby('city').agg({
    'age': ['mean', 'min'],   # average and minimum age
    'name': 'count'           # number of people
})

            age      name
           mean min count
city
Bukhara    31.0  31     1
Samarkand  36.5  28     2
Tashkent   19.5  17     2

In [17]:
# Customers table
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 5],
    'name': ['Ali', 'Zara', 'Jasur', 'Madina', 'Otabek']
})

# Orders table
orders = pd.DataFrame({
    'customer_id': [1, 1, 3],
    'amount': [50000, 75000, 30000]
})

# LEFT JOIN → keep all customers
# If no order → NaN
left = pd.merge(customers, orders, on='customer_id', how='left')

# INNER JOIN → only matched rows
inner = pd.merge(customers, orders, on='customer_id', how='inner')

print('--- LEFT join ---')
print(left)

print('--- INNER join ---')
print(inner)

--- LEFT join ---
   customer_id    name   amount
0            1     Ali  50000.0
1            1     Ali  75000.0
2            2    Zara      NaN
3            3   Jasur  30000.0
4            4  Madina      NaN
5            5  Otabek      NaN
--- INNER join ---
   customer_id   name  amount
0            1    Ali   50000
1            1    Ali   75000
2            3  Jasur   30000

In [18]:
# Region table
regions = pd.DataFrame({
    'city': ['Tashkent', 'Samarkand', 'Bukhara'],
    'region': ['Capital', 'South', 'South']
})

# Add city to customers
customers['city'] = ['Tashkent', 'Samarkand', 'Bukhara', 'Tashkent', 'Samarkand']

# Merge customers with region
cust_region = pd.merge(customers, regions, on='city', how='left')

# Merge with orders
full = pd.merge(cust_region, orders, on='customer_id', how='left')

# Group by region and sum amount
result = full.groupby('region')['amount'].sum()

# Show regions with total > 80000
result[result > 80000]

region
Capital    125000.0
Name: amount, dtype: float64